# 腾讯云TTS配置
tencent_cloud:
  secret_id: "your_secret_id"        # 腾讯云SecretID
  secret_key: "your_secret_key"      # 腾讯云SecretKey  
  region: "ap-beijing"               # 地域
# TTS音频参数配置
# https://cloud.tencent.com/document/product/1073/92668
# 爱小溪  601000 女生
# 爱小静  601005 女生
# 飞镜    501005  男生
# 千璋   501006 男生
# 爱小芊  601009 女生  x

 
# 腾讯TTS音频参数
tts:
  voice_type: 601005      # 音色ID：101008-智琪(女声), 101007-智慧(女声), 101003-智云(男声)
                          # 精品音色如502001可能需要特殊权限，请先测试标准音色
  volume: 5               # 音量：0-10，默认5
  speed: 0.6              # 语速：0.6-1.5，默认1.0
  primary_language: 1     # 主语言：1-中文，2-英文
  sample_rate: 16000      # 采样率：16000/8000
  codec: "mp3"            # 音频格式：mp3/wav

# Edge TTS配置（免费，无需API密钥）
edge_tts:
  voice: "zh-CN-XiaoyiNeural"     # 语音：zh-CN-XiaoyiNeural(晓伊), zh-CN-YunyangNeural(云扬)
                                  # en-US-JennyNeural(珍妮), ja-JP-NanamiNeural(七海)
  rate: "+0%"                     # 语速：-50% 到 +100%，如 +10%, +0%, -20%
  volume: "+0%"                   # 音量：-50% 到 +100%，如 +10%, +0%, -20%  
  pitch: "+0Hz"                   # 音调：-50Hz 到 +50Hz，如 +10Hz, +0Hz, -10Hz


# 音频合并配置
audio:
  output_dir: "./output"          # 输出目录
  temp_dir: "./temp"              # 临时文件目录
  final_output: "merged_audio.mp3" # 最终音频文件名
  silence_duration: 0.5           # 音频片段间隔秒数

# 并发配置
concurrent:
  max_workers: 10                 # 最大并发worker数量
  rate_limit: 20                  # 每秒最大请求数（不超过20次/秒）
  batch_size: 5                   # 批处理大小

# 输入文件配置
input_file: "example_input.txt"      # 默认输入文件路径