version: '3.8'

services:
  tts-app:
    build: .
    image: go-tts-app:latest
    container_name: tts-app
    restart: unless-stopped
    
    # 环境变量
    environment:
      - TTS_CONFIG_FILE=/app/config.yaml
      - TTS_INPUT_FILE=/app/input.txt
      - TTS_OUTPUT_DIR=/app/output
    
    # 卷挂载
    volumes:
      # 配置文件
      - ./config.yaml:/app/config.yaml:ro
      # 输入文件目录
      - ./input:/app/input:ro
      # 输出文件目录
      - ./output:/app/output
      # 临时文件目录
      - ./temp:/app/temp
    
    # 网络设置（如果将来添加Web接口）
    # ports:
    #   - "8080:8080"
    
    # 工作目录
    working_dir: /app
    
    # 默认命令：显示帮助信息
    command: ["edge", "--help"]

  # 如果需要Web界面，可以添加nginx代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: tts-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./output:/usr/share/nginx/html/output:ro
  #   depends_on:
  #     - tts-app

# 网络定义
networks:
  default:
    name: tts-network

# 卷定义
volumes:
  output:
    driver: local
  temp:
    driver: local
